"""
On-This-Day historical facts for Sigmonions daily reminders.
Keys: (month, day).  Feb 29 included for leap years.  Total: 366 entries.
"""

DAILY_HISTORY: dict[tuple[int, int], str] = {

    # ── January ────────────────────────────────────────────────────────────────
    (1,  1): "On this day in 45 BC, Julius Caesar's Julian calendar took effect, introducing the 365-day year still echoed in our modern calendar.",
    (1,  2): "On this day in 1788, Georgia became the 4th state to ratify the US Constitution, setting the Republic in motion.",
    (1,  3): "On this day in 1959, Alaska was admitted as the 49th US state, adding 'the last frontier' to the national vocabulary.",
    (1,  4): "On this day in 1643, Isaac Newton was born — the man who invented calculus and described gravity with a single equation.",
    (1,  5): "On this day in 1895, Charles Duryea drove the first American-made gasoline automobile on a public road in Springfield, Massachusetts.",
    (1,  6): "On this day in 1412, Joan of Arc was born — a teenager who led armies and whose name became a synonym for courage.",
    (1,  7): "On this day in 1714, Henry Mill was granted the first typewriter patent, a machine that would reshape how humanity records its thoughts.",
    (1,  8): "On this day in 1935, Elvis Presley was born in Tupelo, Mississippi — the King whose first name needs no last name.",
    (1,  9): "On this day in 1493, Columbus mistook manatees for mermaids and wrote disappointedly that they were 'not half as beautiful as they are painted.'",
    (1, 10): "On this day in 1863, the world's first underground railway — London's Metropolitan line — opened, making 'the Tube' part of daily life.",
    (1, 11): "On this day in 1569, England held its first national lottery, raising funds for harbour repairs.",
    (1, 12): "On this day in 1773, the first public museum in America opened in Charleston, South Carolina.",
    (1, 13): "On this day in 1128, Pope Honorius II approved the Knights Templar, launching eight centuries of legend and conspiracy theory.",
    (1, 14): "On this day in 1784, the US Congress ratified the Treaty of Paris, officially making American independence a matter of international law.",
    (1, 15): "On this day in 1929, Martin Luther King Jr. was born in Atlanta — the man who gave the world 'I have a dream.'",
    (1, 16): "On this day in 1920, Prohibition took effect in the United States, inadvertently giving the world 'bootlegger,' 'speakeasy,' and 'moonshine.'",
    (1, 17): "On this day in 1706, Benjamin Franklin was born in Boston — statesman, inventor, and author of dozens of proverbs still in daily use.",
    (1, 18): "On this day in 1882, A. A. Milne was born in London — the man who gave the world Winnie-the-Pooh, Eeyore, and the Hundred Acre Wood.",
    (1, 19): "On this day in 1809, Edgar Allan Poe was born in Boston — the master of mystery whose name became synonymous with the macabre.",
    (1, 20): "On this day in 1265, the first English Parliament assembled at Westminster, beginning a tradition of representative government.",
    (1, 21): "On this day in 1954, the USS Nautilus, the world's first nuclear-powered submarine, was launched at Groton, Connecticut.",
    (1, 22): "On this day in 1788, Lord Byron was born — the Romantic poet who coined 'If I should meet thee after long years.'",
    (1, 23): "On this day in 1737, John Hancock was born — the Founding Father whose bold signature made his name a synonym for a personal autograph.",
    (1, 24): "On this day in 1848, James Marshall discovered gold at Sutter's Mill, triggering the California Gold Rush and the phrase 'rush for gold.'",
    (1, 25): "On this day in 1759, Robert Burns was born in Ayrshire — Scotland's national poet, celebrated every year on Burns Night.",
    (1, 26): "On this day in 1788, the First Fleet landed at Sydney Cove, beginning European settlement of Australia.",
    (1, 27): "On this day in 1756, Wolfgang Amadeus Mozart was born in Salzburg — the composer who wrote his first symphony at the age of eight.",
    (1, 28): "On this day in 1754, Horace Walpole coined the word 'serendipity' in a letter, derived from a Persian fairy tale about lucky discoveries.",
    (1, 29): "On this day in 1820, King George III died — the British monarch whose name was etched into the American revolutionary memory.",
    (1, 30): "On this day in 1882, Franklin D. Roosevelt was born — the president who told a nation in crisis, 'the only thing we have to fear is fear itself.'",
    (1, 31): "On this day in 1606, Guy Fawkes was executed in London, his name living on as a word for an effigy and a symbol of political rebellion.",

    # ── February ───────────────────────────────────────────────────────────────
    (2,  1): "On this day in 1884, the first volume of the Oxford English Dictionary was published, beginning the most ambitious word project in history.",
    (2,  2): "On this day in 1709, Alexander Selkirk was rescued after four years on a deserted island — the real-life inspiration for Robinson Crusoe.",
    (2,  3): "On this day in 1468, Johannes Gutenberg died, the man whose movable-type printing press made books — and literacy — accessible to the world.",
    (2,  4): "On this day in 1789, George Washington was unanimously elected the first President of the United States.",
    (2,  5): "On this day in 1850, the first mechanical refrigerator patent was granted to Dr. John Gorrie, beginning the era of ice on demand.",
    (2,  6): "On this day in 1665, cloth from Nîmes, France — 'serge de Nîmes' — was first shipped to the Americas, eventually shortened to the word 'denim.'",
    (2,  7): "On this day in 1812, Charles Dickens was born in Portsmouth — the novelist who gave us 'Scrooge,' 'Pickwickian,' and 'the best of times.'",
    (2,  8): "On this day in 1828, Jules Verne was born in Nantes — the visionary who imagined submarines, space travel, and a trip around the world in 80 days.",
    (2,  9): "On this day in 1773, William Henry Harrison was born — the US president who gave the longest inaugural address and served the shortest term.",
    (2, 10): "On this day in 1763, the Treaty of Paris ended the Seven Years' War, redrawing the map of North America.",
    (2, 11): "On this day in 1847, Thomas Edison was born in Ohio — the inventor who coined 'hello' as the standard telephone greeting.",
    (2, 12): "On this day in 1809, Abraham Lincoln was born in a log cabin in Kentucky — the president who made 'government of the people, by the people' eternal.",
    (2, 13): "On this day in 1633, Galileo arrived in Rome to face the Inquisition for teaching that the Earth revolves around the Sun.",
    (2, 14): "On this day in 270 AD, Saint Valentine was martyred, lending his name to the holiday of romance celebrated worldwide.",
    (2, 15): "On this day in 1564, Galileo Galilei was born in Pisa — the astronomer who first turned a telescope to the night sky.",
    (2, 16): "On this day in 1923, Howard Carter opened the sealed inner chamber of Tutankhamun's tomb, revealing treasures untouched for 3,300 years.",
    (2, 17): "On this day in 1621, Miles Standish was elected military captain of Plymouth Colony, becoming the subject of a famous Longfellow poem.",
    (2, 18): "On this day in 1930, Clyde Tombaugh discovered Pluto — a world later reclassified as a 'dwarf planet' in the great vocabulary shift of 2006.",
    (2, 19): "On this day in 1473, Nicolaus Copernicus was born — the astronomer who placed the Sun, not Earth, at the centre of the universe.",
    (2, 20): "On this day in 1962, John Glenn became the first American to orbit Earth, completing three laps of the planet in under five hours.",
    (2, 21): "On this day in 1848, Marx and Engels published 'The Communist Manifesto,' introducing 'bourgeoisie' and 'proletariat' to everyday language.",
    (2, 22): "On this day in 1732, George Washington was born at Pope's Creek, Virginia — a man whose face graces every dollar bill.",
    (2, 23): "On this day in 1455, printing of the Gutenberg Bible was completed — the first Western book produced with movable type.",
    (2, 24): "On this day in 1582, Pope Gregory XIII issued the papal bull introducing the Gregorian calendar, correcting centuries of accumulated drift.",
    (2, 25): "On this day in 1836, Samuel Colt received a patent for his revolver, adding 'six-shooter' permanently to the American vocabulary.",
    (2, 26): "On this day in 1935, radar was first demonstrated by Robert Watson-Watt — a word coined from 'Radio Detection And Ranging.'",
    (2, 27): "On this day in 1902, John Steinbeck was born in Salinas, California — the novelist who gave us 'the best-laid plans of mice and men.'",
    (2, 28): "On this day in 1983, the final episode of M*A*S*H drew 106 million viewers — still one of the most-watched TV broadcasts in US history.",
    (2, 29): "On this day in 1940, Hattie McDaniel won the Oscar for Best Supporting Actress, becoming the first African American to win an Academy Award.",

    # ── March ──────────────────────────────────────────────────────────────────
    (3,  1): "On this day in 1872, Yellowstone became the world's first national park, inventing the entire concept of protected wilderness.",
    (3,  2): "On this day in 1904, Theodor Seuss Geisel was born — Dr. Seuss, who invented the words 'nerd,' 'grinch,' and a whole universe of nonsense.",
    (3,  3): "On this day in 1847, Alexander Graham Bell was born in Edinburgh — the man who proposed 'ahoy!' as the standard telephone greeting.",
    (3,  4): "On this day in 1789, the US Constitution went into effect, introducing 'We the People' into the vocabulary of democratic government.",
    (3,  5): "On this day in 1770, the Boston Massacre occurred — a skirmish strategically renamed by patriots to inflame public opinion.",
    (3,  6): "On this day in 1475, Michelangelo was born in Caprese, Italy — the artist whose name became the ultimate compliment for any creative genius.",
    (3,  7): "On this day in 1876, Alexander Graham Bell received the patent for the telephone, device number 174,465.",
    (3,  8): "On this day in 1702, Queen Anne ascended the English throne, launching the era that gave its name to Queen Anne architecture and furniture.",
    (3,  9): "On this day in 1454, Amerigo Vespucci was born in Florence — the explorer whose first name, not Columbus's, was given to the Americas.",
    (3, 10): "On this day in 1876, the first words ever spoken over a telephone were 'Mr. Watson — come here — I want to see you.'",
    (3, 11): "On this day in 1888, the Great Blizzard buried New York City under 50 inches of snow and permanently changed how cities plan for winter.",
    (3, 12): "On this day in 1894, Coca-Cola was first sold in bottles, making 'Coke' one of the most recognised brand-words on the planet.",
    (3, 13): "On this day in 1781, William Herschel discovered Uranus — the first planet found with a telescope — naming it after the Greek sky god.",
    (3, 14): "On this day in 1879, Albert Einstein was born in Ulm, Germany — the physicist who turned E=mc² into the world's most famous equation.",
    (3, 15): "On this day in 44 BC, Julius Caesar was assassinated on the Ides of March, giving the world one of history's most ominous phrases.",
    (3, 16): "On this day in 1926, Robert Goddard launched the world's first liquid-fuelled rocket, pioneering the language of 'liftoff' and 'trajectory.'",
    (3, 17): "On this day in 461 AD, St. Patrick — the patron saint whose name became synonymous with shamrocks and parades — died in Ireland.",
    (3, 18): "On this day in 1965, Alexei Leonov became the first human to walk in space, adding 'spacewalk' to the global dictionary.",
    (3, 19): "On this day in 1628, the Petition of Right was presented to King Charles I, enshrining 'habeas corpus' as a cornerstone of English law.",
    (3, 20): "On this day in 1602, the Dutch East India Company was established — the world's first multinational corporation and publicly traded company.",
    (3, 21): "On this day in 1685, Johann Sebastian Bach was born in Eisenach, Germany — the composer who wrote over a thousand works across six decades.",
    (3, 22): "On this day in 1882, the US Edmunds Act outlawed polygamy, sparking one of the 19th century's most contentious legal debates.",
    (3, 23): "On this day in 1775, Patrick Henry delivered his 'Give me liberty, or give me death!' speech — seven words that shook a colony.",
    (3, 24): "On this day in 1989, the Exxon Valdez oil spill began in Alaska, making 'Valdez' a permanent shorthand for environmental disaster.",
    (3, 25): "On this day in 1655, Christiaan Huygens discovered Saturn's moon Titan, expanding the vocabulary of our solar system by one enormous moon.",
    (3, 26): "On this day in 1827, Ludwig van Beethoven died in Vienna — the composer who wrote his greatest symphony while completely deaf.",
    (3, 27): "On this day in 1513, Juan Ponce de León first sighted Florida, naming it 'La Florida' — the flowery land — during Easter week.",
    (3, 28): "On this day in 1868, the first US bicycle club was formed in New York, introducing 'velocipede' to American streets.",
    (3, 29): "On this day in 1848, Niagara Falls stopped flowing for 30 hours when an upstream ice jam cut off the river — a once-in-history silence.",
    (3, 30): "On this day in 1853, Vincent van Gogh was born — the painter who wrote 800 letters describing his work in language as vivid as his brushstrokes.",
    (3, 31): "On this day in 1889, the Eiffel Tower was officially opened in Paris, named after its engineer Gustave Eiffel.",

    # ── April ──────────────────────────────────────────────────────────────────
    (4,  1): "On this day, April Fools' Day is celebrated worldwide — and historians still cannot agree on where the tradition actually began.",
    (4,  2): "On this day in 1860, the Pony Express began service, connecting East and West America until the telegraph made it obsolete just 18 months later.",
    (4,  3): "On this day in 1860, the first Pony Express rider departed St. Joseph, Missouri, carrying mail 1,800 miles to Sacramento.",
    (4,  4): "On this day in 1968, Martin Luther King Jr. was assassinated in Memphis — a loss that silenced one of history's greatest voices.",
    (4,  5): "On this day in 1614, Pocahontas married John Rolfe, cementing a cultural exchange that brought new words between English and Native American languages.",
    (4,  6): "On this day in 1896, the first modern Olympic Games opened in Athens, reviving 'Olympiad' as a living word for athletic excellence.",
    (4,  7): "On this day in 1770, William Wordsworth was born in Cockermouth — the Romantic poet who championed the language of ordinary people.",
    (4,  8): "On this day in 1564, Michelangelo died in Rome, leaving behind a legacy so vast that 'Michelangelo' became shorthand for artistic genius.",
    (4,  9): "On this day in 1865, Robert E. Lee surrendered to Ulysses S. Grant at Appomattox Court House, ending the American Civil War.",
    (4, 10): "On this day in 1912, the RMS Titanic set sail on its maiden voyage, making 'unsinkable' forever one of history's most ironic words.",
    (4, 11): "On this day in 1970, Apollo 13 launched — a mission whose 'Houston, we have a problem' became one of history's most quoted misquotations.",
    (4, 12): "On this day in 1961, Yuri Gagarin became the first human in space, shouting 'Poyekhali!' ('Let's go!') at liftoff.",
    (4, 13): "On this day in 1743, Thomas Jefferson was born in Virginia — the author who introduced 'unalienable rights' into American political vocabulary.",
    (4, 14): "On this day in 1865, Abraham Lincoln was shot at Ford's Theatre, dying the following morning and entering immortality.",
    (4, 15): "On this day in 1452, Leonardo da Vinci was born in Vinci, Italy — the original Renaissance man, engineer, anatomist, and painter.",
    (4, 16): "On this day in 1867, Wilbur Wright was born in Millville, Indiana — the older of the two brothers who proved humans could fly.",
    (4, 17): "On this day in 1790, Benjamin Franklin died in Philadelphia — statesman, inventor, and author of dozens of proverbs still in daily use.",
    (4, 18): "On this day in 1775, Paul Revere made his famous midnight ride warning colonists that British troops were marching on Lexington.",
    (4, 19): "On this day in 1775, the 'shot heard round the world' was fired at Lexington, Massachusetts, beginning the American Revolution.",
    (4, 20): "On this day in 1770, Captain Cook landed at Botany Bay, Australia, introducing hundreds of new plant and animal names to Western science.",
    (4, 21): "On this day in 753 BC, Rome was traditionally founded by Romulus — a city whose name means 'strength' and whose influence spans two millennia.",
    (4, 22): "On this day in 1970, the first Earth Day was celebrated, bringing the word 'ecology' from scientific journals into everyday conversation.",
    (4, 23): "On this day in 1564, William Shakespeare was born in Stratford-upon-Avon — the playwright who gave the English language 1,700 new words.",
    (4, 24): "On this day in 1800, the Library of Congress was established in Washington, D.C., now the largest library in the world.",
    (4, 25): "On this day in 1859, ground was broken for the Suez Canal, linking the Mediterranean and Red Seas across 193 kilometres of desert.",
    (4, 26): "On this day in 1986, the Chernobyl nuclear disaster occurred, making 'meltdown' a permanent part of the global vocabulary.",
    (4, 27): "On this day in 1791, Samuel Morse was born in Massachusetts — the inventor of the code that turned the alphabet into dots and dashes.",
    (4, 28): "On this day in 1789, the mutiny on the HMS Bounty occurred, making 'mutiny' one of the most dramatically charged words in naval history.",
    (4, 29): "On this day in 1429, Joan of Arc arrived to relieve the Siege of Orléans, turning the tide of the Hundred Years' War.",
    (4, 30): "On this day in 1803, the US purchased the Louisiana Territory from France — doubling the country's size for roughly four cents per acre.",

    # ── May ────────────────────────────────────────────────────────────────────
    (5,  1): "On this day in 1931, the Empire State Building officially opened in New York City, the tallest structure in the world for 40 years.",
    (5,  2): "On this day in 1519, Leonardo da Vinci died in France, leaving notebooks that scientists and engineers are still deciphering today.",
    (5,  3): "On this day in 1469, Niccolò Machiavelli was born in Florence — the political theorist whose name gave us the adjective 'Machiavellian.'",
    (5,  4): "On this day in 1979, Margaret Thatcher became Britain's first female Prime Minister, earning the nickname 'The Iron Lady.'",
    (5,  5): "On this day in 1961, Alan Shepard became the first American in space, reporting that everything was 'A-OK' from his capsule.",
    (5,  6): "On this day in 1626, Peter Minuit purchased Manhattan from the Lenape people for goods worth about 60 guilders.",
    (5,  7): "On this day in 1840, Pyotr Ilyich Tchaikovsky was born in Votkinsk — the composer of Swan Lake, The Nutcracker, and 1812 Overture.",
    (5,  8): "On this day in 1945, VE Day marked the Allied victory in Europe, ending six years of war on the continent.",
    (5,  9): "On this day in 1960, the FDA approved the first birth control pill, one of the most socially transformative pharmaceutical decisions in history.",
    (5, 10): "On this day in 1869, the transcontinental railroad was completed at Promontory Summit, Utah, linking America coast to coast by rail.",
    (5, 11): "On this day in 1858, Minnesota became the 32nd US state, carved from lands that the Dakota Sioux had called home for centuries.",
    (5, 12): "On this day in 1820, Florence Nightingale was born in Florence, Italy — the founder of modern nursing and a master of statistical charts.",
    (5, 13): "On this day in 1607, Jamestown was established in Virginia — the first permanent English settlement in the Americas.",
    (5, 14): "On this day in 1804, Lewis and Clark set out from Camp Dubois to explore the American West, a journey that took two and a half years.",
    (5, 15): "On this day in 1860, L. Frank Baum was born — the author who invented Oz, Dorothy, Toto, and a world where ruby slippers are practical.",
    (5, 16): "On this day in 1866, the US Congress authorised the five-cent nickel coin, beginning its long life in pockets and expressions alike.",
    (5, 17): "On this day in 1954, the Supreme Court's Brown v. Board of Education ruling declared racial segregation in public schools unconstitutional.",
    (5, 18): "On this day in 1980, Mount St. Helens erupted in Washington State, one of the most destructive volcanic events in US history.",
    (5, 19): "On this day in 1536, Anne Boleyn was beheaded at the Tower of London, ending one of history's most consequential marriages.",
    (5, 20): "On this day in 1927, Charles Lindbergh began his solo nonstop transatlantic flight — 33.5 hours from New York to Paris.",
    (5, 21): "On this day in 1881, the American Red Cross was founded by Clara Barton, who had spent the Civil War nursing soldiers on the battlefield.",
    (5, 22): "On this day in 1859, Arthur Conan Doyle was born in Edinburgh — the creator of Sherlock Holmes and the phrase 'elementary, my dear Watson.'",
    (5, 23): "On this day in 1785, Benjamin Franklin announced his invention of bifocals in a letter, solving the inconvenience of switching glasses.",
    (5, 24): "On this day in 1844, Samuel Morse sent the first long-distance telegraph message: 'What hath God wrought?' — from Washington to Baltimore.",
    (5, 25): "On this day in 1977, Star Wars premiered, giving pop culture 'The Force,' 'Jedi,' and a galaxy far, far away.",
    (5, 26): "On this day in 1865, the last Confederate general surrendered, officially closing the books on the American Civil War.",
    (5, 27): "On this day in 1937, the Golden Gate Bridge opened in San Francisco, its distinctive International Orange chosen to improve visibility in fog.",
    (5, 28): "On this day in 1908, Ian Fleming was born in London — the creator of James Bond and the phrase 'shaken, not stirred.'",
    (5, 29): "On this day in 1953, Edmund Hillary and Tenzing Norgay became the first people to reach the summit of Mount Everest.",
    (5, 30): "On this day in 1431, Joan of Arc was burned at the stake in Rouen, France — she was 19 years old.",
    (5, 31): "On this day in 1819, Walt Whitman was born — the poet whose 'Leaves of Grass' pioneered free verse and celebrated American democracy.",

    # ── June ───────────────────────────────────────────────────────────────────
    (6,  1): "On this day in 1926, Marilyn Monroe was born in Los Angeles — an actress whose first name alone became a synonym for Hollywood glamour.",
    (6,  2): "On this day in 1953, Queen Elizabeth II was crowned at Westminster Abbey, a ceremony watched by 27 million television viewers.",
    (6,  3): "On this day in 1621, the Dutch West India Company received its charter, establishing trade routes that spread Dutch words across the globe.",
    (6,  4): "On this day in 1940, Churchill delivered his 'We shall fight on the beaches' speech — perhaps the most rousing address of the 20th century.",
    (6,  5): "On this day in 1883, John Maynard Keynes was born in Cambridge — the economist whose ideas reshaped how governments manage money.",
    (6,  6): "On this day in 1944, Allied forces landed at Normandy on D-Day — the largest seaborne invasion in the history of warfare.",
    (6,  7): "On this day in 1954, Alan Turing died — the father of computer science who gave his name to the 'Turing Test' for machine intelligence.",
    (6,  8): "On this day in 1786, the first ice cream parlour in America opened in New York City.",
    (6,  9): "On this day in 1672, Peter the Great was born in Moscow — the tsar who modernised Russia and introduced hundreds of European words into Russian.",
    (6, 10): "On this day in 1752, Benjamin Franklin flew his kite in a thunderstorm, proving that lightning is electricity.",
    (6, 11): "On this day in 1963, Valentina Tereshkova became the first woman in space, orbiting Earth 48 times aboard Vostok 6.",
    (6, 12): "On this day in 1665, the Duke's Laws established the first English legal code for settlers in what would become New York.",
    (6, 13): "On this day in 323 BC, Alexander the Great died in Babylon at age 32, having spread Greek language and culture across three continents.",
    (6, 14): "On this day in 1777, the Continental Congress adopted the Stars and Stripes as the official flag of the United States.",
    (6, 15): "On this day in 1215, King John signed the Magna Carta at Runnymede, establishing that even kings are subject to the law.",
    (6, 16): "On this day in 1904, James Joyce set 'Ulysses' — June 16 is now celebrated as Bloomsday by readers worldwide in Dublin and beyond.",
    (6, 17): "On this day in 1885, the Statue of Liberty arrived in New York Harbor in 214 crates, a gift of friendship from France.",
    (6, 18): "On this day in 1815, Napoleon was defeated at Waterloo, giving the world the phrase 'meeting one's Waterloo' for a decisive defeat.",
    (6, 19): "On this day in 1865, enslaved people in Texas learned of the Emancipation Proclamation — two and a half years after it was signed.",
    (6, 20): "On this day in 1782, the Great Seal of the United States was adopted, bearing the Latin motto 'E Pluribus Unum' — Out of Many, One.",
    (6, 21): "On this day in 1788, New Hampshire ratified the US Constitution, becoming the ninth state and making the Constitution the law of the land.",
    (6, 22): "On this day in 1633, Galileo was forced to recant his heliocentric views, reportedly muttering 'And yet it moves' under his breath.",
    (6, 23): "On this day in 1868, Christopher Sholes patented the QWERTY typewriter keyboard, shaping the layout of every keyboard ever since.",
    (6, 24): "On this day in 1374, a dancing mania broke out in Aachen — hundreds of people danced uncontrollably for days in a phenomenon never fully explained.",
    (6, 25): "On this day in 1876, the Battle of Little Bighorn took place — also known as 'Custer's Last Stand,' a phrase still used for doomed last efforts.",
    (6, 26): "On this day in 1945, the United Nations Charter was signed in San Francisco by representatives of 50 nations.",
    (6, 27): "On this day in 1880, Helen Keller was born in Tuscumbia, Alabama — she would go on to master five languages despite being deaf and blind.",
    (6, 28): "On this day in 1914, Archduke Franz Ferdinand was assassinated in Sarajevo — a single shot that triggered the First World War.",
    (6, 29): "On this day in 1613, Shakespeare's Globe Theatre burned to the ground during a performance of Henry VIII.",
    (6, 30): "On this day in 1859, Charles Blondin crossed Niagara Falls on a tightrope for the first time, in front of thousands of spectators.",

    # ── July ───────────────────────────────────────────────────────────────────
    (7,  1): "On this day in 1867, Canada became a self-governing dominion — now celebrated annually as Canada Day.",
    (7,  2): "On this day in 1937, Amelia Earhart and Fred Noonan disappeared over the Pacific while attempting a round-the-world flight.",
    (7,  3): "On this day in 1863, the three-day Battle of Gettysburg ended — the bloodiest battle of the American Civil War.",
    (7,  4): "On this day in 1776, the Declaration of Independence was adopted, introducing 'unalienable rights' to the world's political vocabulary.",
    (7,  5): "On this day in 1687, Isaac Newton published 'Principia Mathematica,' one of the most important scientific books ever written.",
    (7,  6): "On this day in 1415, Jan Hus was burned at the stake for heresy in Constance, inspiring a religious movement that bore his name.",
    (7,  7): "On this day in 1456, Joan of Arc was posthumously acquitted of heresy — 25 years after she was executed for it.",
    (7,  8): "On this day in 1835, the Liberty Bell cracked while tolling for the funeral of Chief Justice John Marshall.",
    (7,  9): "On this day in 1850, Millard Fillmore became the 13th US President after Zachary Taylor died of acute gastroenteritis in office.",
    (7, 10): "On this day in 1856, Nikola Tesla was born in Croatia — the inventor whose name now measures the strength of magnetic fields.",
    (7, 11): "On this day in 1804, Aaron Burr fatally shot Alexander Hamilton in a duel in Weehawken, New Jersey.",
    (7, 12): "On this day in 100 BC, Julius Caesar was born — the Roman general who gave his name to a salad, a month, and a surgical procedure.",
    (7, 13): "On this day in 1837, Queen Victoria moved into Buckingham Palace, establishing it as the official London residence of the British monarch.",
    (7, 14): "On this day in 1789, French revolutionaries stormed the Bastille fortress-prison — a day now celebrated as Bastille Day in France.",
    (7, 15): "On this day in 1799, the Rosetta Stone was discovered in Egypt, unlocking the mystery of ancient Egyptian hieroglyphics.",
    (7, 16): "On this day in 1969, Apollo 11 launched from Kennedy Space Center on humanity's first mission to land on the Moon.",
    (7, 17): "On this day in 1955, Disneyland opened in Anaheim, California, introducing 'imagineering' and theme-park design to the world.",
    (7, 18): "On this day in 64 AD, the Great Fire of Rome began — an event that Nero notoriously watched, inspiring the phrase 'fiddling while Rome burns.'",
    (7, 19): "On this day in 1848, the first women's rights convention was held at Seneca Falls, New York, launching the suffragist movement.",
    (7, 20): "On this day in 1969, Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon.",
    (7, 21): "On this day in 1899, Ernest Hemingway was born in Oak Park, Illinois — the novelist who proved that short sentences could carry enormous weight.",
    (7, 22): "On this day in 1796, Cleveland, Ohio was founded by General Moses Cleaveland, whose name lost a vowel when the town printed its first newspaper.",
    (7, 23): "On this day in 1829, William Austin Burt received a patent for his 'typographer,' an early mechanical writing machine.",
    (7, 24): "On this day in 1911, Hiram Bingham encountered Machu Picchu, bringing the 'Lost City of the Incas' to the attention of the world.",
    (7, 25): "On this day in 1978, Louise Brown was born in Oldham, England — the world's first baby conceived through in vitro fertilisation.",
    (7, 26): "On this day in 1775, the Continental Congress established the United States Post Office with Benjamin Franklin as Postmaster General.",
    (7, 27): "On this day in 1953, the armistice ending the Korean War was signed — a conflict that is technically still not over by formal peace treaty.",
    (7, 28): "On this day in 1914, Austria-Hungary declared war on Serbia, setting in motion the chain of alliances that began World War I.",
    (7, 29): "On this day in 1981, Prince Charles married Lady Diana Spencer in a ceremony watched by an estimated 750 million television viewers.",
    (7, 30): "On this day in 1863, Henry Ford was born in Dearborn, Michigan — the industrialist who gave the world the assembly line and the Model T.",
    (7, 31): "On this day in 1790, the first US patent was signed by President Washington — granted to Samuel Hopkins for a potash-making process.",

    # ── August ─────────────────────────────────────────────────────────────────
    (8,  1): "On this day in 1834, the Slavery Abolition Act took effect throughout the British Empire, freeing approximately 800,000 enslaved people.",
    (8,  2): "On this day in 1876, Wild Bill Hickok was shot while holding aces and eights — a poker hand forever known as the 'Dead Man's Hand.'",
    (8,  3): "On this day in 1492, Columbus set sail from Palos, Spain on his first voyage into the unknown Atlantic.",
    (8,  4): "On this day in 1753, George Washington was raised to Master Mason, beginning the founding father's lifelong connection to Freemasonry.",
    (8,  5): "On this day in 1858, the first transatlantic telegraph cable was completed, allowing messages between Europe and America in minutes.",
    (8,  6): "On this day in 1945, the atomic bomb was dropped on Hiroshima, Japan — an event that reshaped global vocabulary and world order.",
    (8,  7): "On this day in 1782, George Washington established the Purple Heart, originally called the 'Badge of Military Merit.'",
    (8,  8): "On this day in 1974, Richard Nixon announced his resignation as US President — the only person to resign from the office.",
    (8,  9): "On this day in 1945, the atomic bomb was dropped on Nagasaki — three days after Hiroshima, and the last nuclear weapon ever used in war.",
    (8, 10): "On this day in 1846, the Smithsonian Institution was established in Washington, D.C., funded by a British scientist who never visited America.",
    (8, 11): "On this day in 3114 BC (by one reckoning), the Maya Long Count calendar began — a system so precise it predicted astronomical events centuries in advance.",
    (8, 12): "On this day in 1851, Isaac Singer was granted a patent for his sewing machine, which would transform the garment industry worldwide.",
    (8, 13): "On this day in 1521, Spanish forces defeated the Aztec capital Tenochtitlán, bringing words like 'chocolate,' 'tomato,' and 'avocado' to Europe.",
    (8, 14): "On this day in 1945, Japan announced its unconditional surrender, ending World War II and the deadliest conflict in human history.",
    (8, 15): "On this day in 1769, Napoleon Bonaparte was born in Corsica — the emperor whose name inspired 'Napoleonic,' 'Napoleon complex,' and a pastry.",
    (8, 16): "On this day in 1977, Elvis Presley died at Graceland, Tennessee — the King of Rock and Roll, aged just 42.",
    (8, 17): "On this day in 1896, Roald Dahl was born in Wales — the author who invented words like 'scrumdiddlyumptious' and 'whizzpopping.'",
    (8, 18): "On this day in 1587, Virginia Dare became the first English child born in the Americas, in the colony of Roanoke that would soon vanish.",
    (8, 19): "On this day in 1848, the New York Herald confirmed the discovery of gold in California, transforming the word 'rush' into a mass migration.",
    (8, 20): "On this day in 1940, Churchill said of the RAF: 'Never in the field of human conflict was so much owed by so many to so few.'",
    (8, 21): "On this day in 1959, Hawaii became the 50th US state, adding 'aloha,' 'luau,' and 'hula' to the American vocabulary.",
    (8, 22): "On this day in 1485, the Battle of Bosworth Field ended with Richard III dead and Henry Tudor claiming the English crown.",
    (8, 23): "On this day in 1305, William Wallace was executed in London — the Scottish hero whose resistance inspired the word 'braveheart.'",
    (8, 24): "On this day in 79 AD, Mount Vesuvius erupted, burying Pompeii under volcanic ash and preserving a Roman city for nearly 2,000 years.",
    (8, 25): "On this day in 1835, the 'Great Moon Hoax' began — a series of articles falsely claiming life had been discovered on the Moon.",
    (8, 26): "On this day in 1920, the 19th Amendment was certified, guaranteeing American women the right to vote.",
    (8, 27): "On this day in 1883, Krakatoa erupted in Indonesia, producing the loudest sound in recorded history — heard 3,000 miles away.",
    (8, 28): "On this day in 1963, Martin Luther King Jr. delivered his 'I Have a Dream' speech before 250,000 people on the National Mall.",
    (8, 29): "On this day in 1831, Michael Faraday demonstrated electromagnetic induction, laying the groundwork for every electric motor ever built.",
    (8, 30): "On this day in 1797, Mary Shelley was born — the author of 'Frankenstein' and the inventor of the science fiction genre.",
    (8, 31): "On this day in 1897, Thomas Edison patented the Kinetoscope, an early motion-picture device that was the great-grandfather of cinema.",

    # ── September ──────────────────────────────────────────────────────────────
    (9,  1): "On this day in 1939, Nazi Germany invaded Poland, beginning the Second World War.",
    (9,  2): "On this day in 1666, the Great Fire of London started in a bakery on Pudding Lane and burned for four days, destroying 13,200 houses.",
    (9,  3): "On this day in 1783, the Treaty of Paris was signed, formally recognising American independence from Britain.",
    (9,  4): "On this day in 1886, Geronimo surrendered to US forces, ending the last major armed resistance of a Native American nation.",
    (9,  5): "On this day in 1698, Peter the Great imposed a tax on beards in Russia, part of his campaign to westernise Russian society.",
    (9,  6): "On this day in 1522, the Victoria completed the first circumnavigation of the globe, proving the Earth was round by simply going all the way around.",
    (9,  7): "On this day in 1533, Queen Elizabeth I was born — the 'Virgin Queen' whose 45-year reign defined the Elizabethan era.",
    (9,  8): "On this day in 1504, Michelangelo's 17-foot marble 'David' was unveiled in Florence's Piazza della Signoria.",
    (9,  9): "On this day in 1776, the Continental Congress officially replaced 'United Colonies' with 'United States' in all government documents.",
    (9, 10): "On this day in 1846, Elias Howe patented the sewing machine, a device that would transform how clothes — and the word 'fashion' — worked.",
    (9, 11): "On this day in 2001, the September 11 attacks reshaped America and global vocabulary with terms like 'homeland security' and 'War on Terror.'",
    (9, 12): "On this day in 1959, the Soviet Luna 2 became the first spacecraft to reach the surface of the Moon.",
    (9, 13): "On this day in 1788, New York City was designated the first capital of the United States.",
    (9, 14): "On this day in 1901, President William McKinley died of his wounds, making Theodore Roosevelt — at 42 — the youngest US president in history.",
    (9, 15): "On this day in 1857, William Howard Taft was born — the only person in American history to serve as both President and Chief Justice.",
    (9, 16): "On this day in 1620, the Mayflower set sail from Plymouth, England, carrying 102 Pilgrims toward the New World.",
    (9, 17): "On this day in 1787, thirty-nine delegates signed the United States Constitution in Philadelphia.",
    (9, 18): "On this day in 1793, George Washington laid the cornerstone of the US Capitol Building.",
    (9, 19): "On this day in 1796, Washington delivered his Farewell Address, warning against 'permanent alliances' — advice debated for centuries.",
    (9, 20): "On this day in 1519, Ferdinand Magellan set out on the voyage that would become the first circumnavigation of the globe.",
    (9, 21): "On this day in 1937, J. R. R. Tolkien published 'The Hobbit,' introducing Middle-earth, the One Ring, and a fully invented language.",
    (9, 22): "On this day in 1692, the last executions took place in the Salem witch trials — one of America's most cautionary episodes of mass hysteria.",
    (9, 23): "On this day in 1806, Lewis and Clark returned to St. Louis after their epic 28-month expedition across the American continent.",
    (9, 24): "On this day in 1789, the Judiciary Act established the US Supreme Court and the office of Attorney General.",
    (9, 25): "On this day in 1789, the US Congress passed the Bill of Rights — ten amendments that defined the limits of government power.",
    (9, 26): "On this day in 1774, John Chapman (Johnny Appleseed) was born in Massachusetts — a man whose legend grew as tall as his apple trees.",
    (9, 27): "On this day in 1905, Albert Einstein published his paper on special relativity, giving the world E=mc².",
    (9, 28): "On this day in 551 BC, Confucius was born in Qufu, China — a philosopher whose 'Confucian' wisdom shaped Eastern thought for 2,500 years.",
    (9, 29): "On this day in 1571, the Battle of Lepanto was fought — the last great naval battle conducted entirely with oar-powered galleys.",
    (9, 30): "On this day in 1955, James Dean died in a car crash in California — the actor who gave a face to the phrase 'rebel without a cause.'",

    # ── October ────────────────────────────────────────────────────────────────
    (10,  1): "On this day in 1908, Ford introduced the Model T, making automobiles affordable and putting 'full throttle' into everyday speech.",
    (10,  2): "On this day in 1869, Mahatma Gandhi was born in Gujarat — the leader whose concept of 'satyagraha' (truth-force) inspired nonviolent movements worldwide.",
    (10,  3): "On this day in 1863, President Lincoln proclaimed Thanksgiving a national holiday, giving it a permanent home on the calendar.",
    (10,  4): "On this day in 1957, the Soviet Union launched Sputnik 1 — the first artificial satellite to orbit Earth.",
    (10,  5): "On this day in 1962, the Beatles released their debut single 'Love Me Do,' launching the career of the most influential band in pop history.",
    (10,  6): "On this day in 1927, 'The Jazz Singer' premiered — the first feature film with synchronised dialogue, making silent pictures obsolete overnight.",
    (10,  7): "On this day in 1849, Edgar Allan Poe died in Baltimore — the master of macabre who coined the word 'tintinnabulation.'",
    (10,  8): "On this day in 1871, the Great Chicago Fire broke out, supposedly when Mrs. O'Leary's cow kicked over a lantern — a legend that outlived the evidence.",
    (10,  9): "On this day in 1635, Roger Williams was expelled from Massachusetts for advocating religious tolerance and the separation of church and state.",
    (10, 10): "On this day in 1886, the tuxedo dinner jacket was first worn at the Tuxedo Club in New York, adding 'black tie' to fashion's vocabulary.",
    (10, 11): "On this day in 1975, Saturday Night Live premiered on NBC, launching a comedy institution that coined 'Not ready for prime time.'",
    (10, 12): "On this day in 1492, Christopher Columbus reached the Bahamas — marking Europe's first contact with the Americas.",
    (10, 13): "On this day in 1792, the cornerstone of the White House was laid in Washington, D.C.",
    (10, 14): "On this day in 1066, the Battle of Hastings transformed the English language forever by blending Anglo-Saxon with Norman French.",
    (10, 15): "On this day in 1844, Friedrich Nietzsche was born — the philosopher who gave us 'What does not kill me makes me stronger.'",
    (10, 16): "On this day in 1793, Marie Antoinette was guillotined in Paris — the queen whose 'Let them eat cake' remains history's most disputed quotation.",
    (10, 17): "On this day in 1849, Frédéric Chopin died in Paris — the composer who made the piano speak in voices that still feel entirely human.",
    (10, 18): "On this day in 1867, the US purchased Alaska from Russia for 7.2 million dollars — initially mocked by the press as 'Seward's Folly.'",
    (10, 19): "On this day in 1781, British General Cornwallis surrendered at Yorktown — effectively ending the American Revolutionary War.",
    (10, 20): "On this day in 1818, the US-Canada border was fixed at the 49th parallel, establishing the world's longest undefended international border.",
    (10, 21): "On this day in 1879, Thomas Edison successfully tested the incandescent light bulb, turning darkness into a design problem.",
    (10, 22): "On this day in 1836, Sam Houston was inaugurated as the first president of the Republic of Texas.",
    (10, 23): "On this day in 4004 BC (by Bishop Ussher's famous calculation), the Earth was created — a date that sparked centuries of scientific debate.",
    (10, 24): "On this day in 1945, the United Nations officially came into existence, introducing 'international law' as the basis for global peace.",
    (10, 25): "On this day in 1881, Pablo Picasso was born in Málaga, Spain — the artist whose name became the definition of creative reinvention.",
    (10, 26): "On this day in 1881, the gunfight at the O.K. Corral took place in Tombstone — 30 seconds that became an American legend.",
    (10, 27): "On this day in 1858, Theodore Roosevelt was born — the president who coined 'bully pulpit' and who gave teddy bears their name.",
    (10, 28): "On this day in 1886, the Statue of Liberty was dedicated in New York Harbor — a gift from France bearing the torch of liberty.",
    (10, 29): "On this day in 1929, Black Tuesday triggered the Great Depression, adding 'breadline,' 'hobo,' and 'Hooverville' to the American lexicon.",
    (10, 30): "On this day in 1938, Orson Welles' radio broadcast of 'War of the Worlds' caused widespread panic across America.",
    (10, 31): "On this day in 1517, Martin Luther nailed his 95 Theses to a church door in Wittenberg, igniting the Protestant Reformation.",

    # ── November ───────────────────────────────────────────────────────────────
    (11,  1): "On this day in 1512, the Sistine Chapel ceiling was unveiled to the public, revealing Michelangelo's masterpiece of biblical storytelling.",
    (11,  2): "On this day in 1947, Howard Hughes flew the Spruce Goose — the largest wooden aircraft ever built — on its one and only flight.",
    (11,  3): "On this day in 1957, the Soviet Union launched Sputnik 2 with the dog Laika aboard — the first living creature to orbit Earth.",
    (11,  4): "On this day in 1842, Abraham Lincoln married Mary Todd in Springfield, Illinois.",
    (11,  5): "On this day in 1605, Guy Fawkes and his co-conspirators were caught beneath Parliament with barrels of gunpowder, their plot foiled.",
    (11,  6): "On this day in 1860, Abraham Lincoln was elected the 16th President — a result so divisive that Southern states began seceding within weeks.",
    (11,  7): "On this day in 1867, Marie Curie was born in Warsaw — the first person to win two Nobel Prizes in two different scientific fields.",
    (11,  8): "On this day in 1895, Wilhelm Röntgen discovered X-rays — giving medicine a revolutionary tool and physics a genuinely mysterious name.",
    (11,  9): "On this day in 1989, the Berlin Wall fell — and 'tearing down walls' became the defining metaphor of a generation.",
    (11, 10): "On this day in 1775, the United States Marine Corps was founded at Tun Tavern in Philadelphia.",
    (11, 11): "On this day in 1918, World War I ended at the 11th hour of the 11th day of the 11th month — a ceasefire so precise it became symbolic.",
    (11, 12): "On this day in 1035, King Canute the Great died, famous for the parable of commanding the tide — a lesson in the limits of royal authority.",
    (11, 13): "On this day in 1850, Robert Louis Stevenson was born in Edinburgh — the author of 'Treasure Island' and creator of Long John Silver.",
    (11, 14): "On this day in 1765, Robert Fulton was born in Pennsylvania — the inventor whose steamboat put 'full steam ahead' on the map.",
    (11, 15): "On this day in 1908, SOS was officially adopted as the international distress signal, replacing CQD with a pattern easier to transmit.",
    (11, 16): "On this day in 1532, Francisco Pizarro captured Inca Emperor Atahualpa at Cajamarca — one of history's most consequential ambushes.",
    (11, 17): "On this day in 1869, the Suez Canal formally opened, cutting 7,000 kilometres off the sea route from Europe to Asia.",
    (11, 18): "On this day in 1307, William Tell supposedly shot an apple off his son's head with a crossbow — a legend that became national myth.",
    (11, 19): "On this day in 1863, Lincoln delivered the Gettysburg Address — 272 words that redefined the meaning of the American experiment.",
    (11, 20): "On this day in 1789, New Jersey became the first state to ratify the US Bill of Rights.",
    (11, 21): "On this day in 1789, North Carolina ratified the US Constitution, becoming the 12th state in the union.",
    (11, 22): "On this day in 1963, President John F. Kennedy was assassinated in Dallas, Texas.",
    (11, 23): "On this day in 1963, 'Doctor Who' premiered on the BBC — the beginning of the world's longest-running science fiction television series.",
    (11, 24): "On this day in 1859, Charles Darwin published 'On the Origin of Species,' introducing 'evolution' and 'natural selection' to science.",
    (11, 25): "On this day in 1867, Alfred Nobel patented dynamite — and later established the Nobel Prizes to ensure he was remembered differently.",
    (11, 26): "On this day in 1789, George Washington declared the first national Thanksgiving Day at the request of Congress.",
    (11, 27): "On this day in 1703, the Great Storm of 1703 battered Britain for two days — the most destructive storm in recorded British history.",
    (11, 28): "On this day in 1520, Magellan's fleet entered the Pacific Ocean through the strait now named in his honour.",
    (11, 29): "On this day in 1832, Louisa May Alcott was born in Pennsylvania — the author of 'Little Women' and a tireless advocate for women's rights.",
    (11, 30): "On this day in 1667, Jonathan Swift was born in Dublin — the satirist who gave the world 'Lilliputian,' 'Yahoo,' and 'Gulliver.'",

    # ── December ───────────────────────────────────────────────────────────────
    (12,  1): "On this day in 1955, Rosa Parks refused to give up her seat on a Montgomery bus — an act of quiet courage that ignited the Civil Rights Movement.",
    (12,  2): "On this day in 1804, Napoleon Bonaparte crowned himself Emperor of France — reaching the summit of ambition in the most literal sense possible.",
    (12,  3): "On this day in 1833, Oberlin College in Ohio became the first college in the US to admit women.",
    (12,  4): "On this day in 1791, The Observer was published for the first time in London — the world's oldest Sunday newspaper.",
    (12,  5): "On this day in 1848, President Polk confirmed the California gold discovery in a message to Congress, triggering a national stampede.",
    (12,  6): "On this day in 1865, the 13th Amendment was ratified — abolishing slavery and rewriting the meaning of freedom in the United States.",
    (12,  7): "On this day in 1941, Japan attacked Pearl Harbor — a day President Roosevelt said would 'live in infamy.'",
    (12,  8): "On this day in 1980, John Lennon was shot outside his apartment in New York City — a loss felt around the world.",
    (12,  9): "On this day in 1868, William Gladstone became British Prime Minister for the first time, beginning a political career that would span 60 years.",
    (12, 10): "On this day in 1901, the first Nobel Prizes were awarded in Stockholm, honouring achievement in physics, chemistry, medicine, literature, and peace.",
    (12, 11): "On this day in 1936, Edward VIII abdicated the British throne, delivering a radio broadcast that began: 'I have found it impossible to carry on...'",
    (12, 12): "On this day in 1901, Guglielmo Marconi received the first transatlantic radio signal in St. John's, Newfoundland — sent from Cornwall, England.",
    (12, 13): "On this day in 1577, Sir Francis Drake set out from Plymouth on his voyage to circumnavigate the globe.",
    (12, 14): "On this day in 1911, Roald Amundsen's team became the first to reach the South Pole, beating Robert Scott by 34 days.",
    (12, 15): "On this day in 1791, the US Bill of Rights was ratified, adding the first ten amendments to the Constitution.",
    (12, 16): "On this day in 1773, American colonists disguised as Mohawks dumped 342 chests of British tea into Boston Harbor.",
    (12, 17): "On this day in 1903, Orville and Wilbur Wright made the first successful powered airplane flight at Kitty Hawk, North Carolina.",
    (12, 18): "On this day in 1737, Antonio Stradivari died in Cremona, Italy — the luthier whose name became the gold standard for a musical instrument.",
    (12, 19): "On this day in 1843, Charles Dickens published 'A Christmas Carol,' giving the world 'Bah, humbug!' and 'Scrooge' as a permanent synonym for miser.",
    (12, 20): "On this day in 1803, the Louisiana Purchase was finalised, transferring 828,000 square miles from France to the United States.",
    (12, 21): "On this day in 1620, the Mayflower Pilgrims went ashore at Plymouth, Massachusetts, for the first time.",
    (12, 22): "On this day in 1894, Captain Alfred Dreyfus was wrongly convicted of treason in France — launching one of history's great miscarriages of justice.",
    (12, 23): "On this day in 1888, Vincent van Gogh cut off part of his own ear after an argument with Gauguin, wrapping it as a gift — art history's strangest story.",
    (12, 24): "On this day in 1818, 'Silent Night' was performed for the first time at St. Nicholas Church in Oberndorf, Austria.",
    (12, 25): "On this day in 800 AD, Charlemagne was crowned Holy Roman Emperor on Christmas Day, unifying Western Europe under a single crown.",
    (12, 26): "On this day in 1898, Marie and Pierre Curie announced their discovery of radium, a word they coined from the Latin 'radius' meaning ray.",
    (12, 27): "On this day in 1831, Charles Darwin set sail on HMS Beagle — a voyage that would eventually overturn humanity's understanding of its own origins.",
    (12, 28): "On this day in 1879, the Tay Bridge in Scotland collapsed during a storm, killing 75 people and inspiring what many consider the worst poem in English.",
    (12, 29): "On this day in 1845, Texas was admitted to the United States as the 28th state.",
    (12, 30): "On this day in 1853, the Gadsden Purchase was finalised, adding the last piece of land to the continental United States.",
    (12, 31): "On this day in 1600, the British East India Company was founded — a trading firm that would eventually rule large parts of a subcontinent.",
}


def get_fact_for(month: int, day: int) -> str:
    """Return the history fact for (month, day), with a safe fallback."""
    return DAILY_HISTORY.get(
        (month, day),
        "On this day, word lovers around the world are discovering that every category has a secret connection.",
    )
